- environment/environment.py
- run_ibis_tests.py
- run_omnisci_benchmark.py
It is better to use conda api functions instead of Popen process because of catching exceptions possibility with use_exception_handler
> Use conda api to execute conda commands

- santander/santander_ibis.py
- server_worker/server_worker.py
Changes description are there https://jira.devtools.intel.com/browse/ARROW-109?focusedCommentId=7651413&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-7651413.
> [Santander] Queries validation operations

- taxi/taxibench_pandas.py
https://teamcity-or.intel.com/viewLog.html?buildId=4987038&buildTypeId=Golang_Omniscidb_TestOnly&tab=buildLog#_state=1345,1661
[Step 9/13] Traceback (most recent call last):
[01:46:55][Step 9/13]   File "taxi/taxibench_pandas.py", line 196, in <module>
[01:46:55][Step 9/13]     db = mysql.connector.connect(
[01:46:55][Step 9/13] NameError: name 'mysql' is not defined
[01:46:55][Step 9/13] Process exited with code 1
> Fix taxibench_pandas.py in CI

- environment/environment.py
- santander/santander_pandas_ibis.py
> add printing conda packages

- santander/santander_pandas_ibis.py
This change is needed for proper run of CI.
> [Santander]: Correction of outdated attribute

- ci_requirements.yml
depends on https://github.com/intel-go/ibis/pull/ 13 - MERGED
> remove pymapd

- census/census_pandas_ibis.py
- plasticc/plasticc_pandas_ibis.py
- santander/santander_pandas_ibis.py
- server_worker/server_worker.py
depends on:
- ibis' PR https://github.com/ibis-project/ibis/pull/ 2154
- pymapd' PR https://github.com/omnisci/pymapd/pull/ 303
> fix TSocker error

- census/census_pandas_ibis.py
- plasticc/plasticc_pandas_ibis.py
- report/report.py
- run_ibis_benchmark.py
- santander/santander_pandas_ibis.py
- server_worker/server_worker.py
- taxi/taxibench_pandas_ibis.py
- teamcity_build_scripts/14-ny_taxi_pandas_ibis.sh
- teamcity_build_scripts/15-santander_pandas_ibis.sh
- teamcity_build_scripts/16-census_pandas_ibis.sh
- teamcity_build_scripts/17-plasticc_pandas_ibis.sh
- utils/__init__.py
- utils/utils.py
Introduced changes are done for proper results reporting to MySQL database.
> Refactoring corrections

- census/census_pandas_ibis.py
- mortgage/mortgage_ibis.py
- mortgage/mortgage_runner.py
- plasticc/plasticc_pandas_ibis.py
- run_ibis_tests.py
- santander/santander_pandas_ibis.py
- teamcity_build_scripts/15-santander_pandas_ibis.sh
- teamcity_build_scripts/16-census_pandas_ibis.sh
- teamcity_build_scripts/18-mortgage.sh
- utils/__init__.py
- utils/utils.py
also fix passing fragments_size through run_ibis_tests.py
> add fragments_size option for census, santander and mortgage workloads

- teamcity_build_scripts/02-build_ibis.sh
- teamcity_build_scripts/04-ibis_test.sh
- teamcity_build_scripts/05-synthetic_BaselineHash.sh
- teamcity_build_scripts/06-synthetic_MultiStep.sh
- teamcity_build_scripts/07-synthetic_NonGroupedAgg.sh
- teamcity_build_scripts/08-synthetic_PerfectHashMultiCol.sh
- teamcity_build_scripts/09-synthetic_PerfectHashSingleCol.sh
- teamcity_build_scripts/10-synthetic_Sort.sh
- teamcity_build_scripts/11-flights_7M.sh
- teamcity_build_scripts/12-ny_taxi_1_file.sh
- teamcity_build_scripts/13-ny_taxi_20_files.sh
- teamcity_build_scripts/14-ny_taxi_pandas_ibis.sh
- teamcity_build_scripts/15-santander_pandas_ibis.sh
this PR makes teamcity scripts more readable and updates outdated arguments names
> Teamcity scripts refactoring

- README.md
- taxi/taxibench_pandas_ibis.py
- utils/__init__.py
- utils/utils.py
These corrections determine process of searching preprocessed csv file for fsi import.
> [taxi]: fsi correction

- plasticc/plasticc_pandas_ibis.py
- santander/santander_pandas_ibis.py
- utils/utils.py
> Multiprocessing for validation

- README.md
- taxi/taxibench_pandas_ibis.py
This change allows to import taxi data by fsi (tested on the full dataset).
> [taxi] change data type for two fields

- mortgage/mortgage_ibis.py
Found timing readcsv problem for multiple perf files, and fixed it.
> fix readcsv timer problem

- run_ibis_benchmark.py
- utils/__init__.py
- utils/utils.py
This PR separates reporting to the function and extends functional with capability to process subqueries like it is needed in https://github.com/intel-go/omniscripts/pull/113.
> Refactor reporting

- mortgage/mortgage_pandas.py
- mortgage/mortgage_runner.py
Also adds a bunch of (debug) prints to help see progress.
> Add support for getting mortgage data from http/s3 sources

- run_ibis_benchmark.py
- run_ibis_tests.py
- taxi/taxibench_pandas_ibis.py
Both Ibis and Pandas queries outputs aligned to match original SQL queries outputs from https://tech.marksblogg.com/billion-nyc-taxi-rides-nvidia-pascal-titan-x-mapd.html.
Corresponding Jira ticket number is 275 (see for results comparison).
> [taxi] Queries outputs aligning

- ci_requirements.yml
- utils/utils.py
> Add support for getting taxi data from s3/https sources

- h2o/h2o_modin.py
- utils/__init__.py
- utils/utils.py
> Add support for getting h2o data from s3/https sources

- utils/utils.py
> fix getsize for s3 links

- mortgage/mortgage_runner.py
- utils/__init__.py
- utils/utils.py
We need to know dataset size for calculation of throughput rate for results representation in Grafana.
> [Mortgage] add reporting of dataset size

- taxi/taxibench_pandas_ibis.py
q3_pandas equivalent implementation change to make query implementation more suitable for use with Modin and better match SQL version.
> [taxi] correct q3_pandas implementation

- mortgage/mortgage.py
- mortgage/mortgage_pandas.py
- plasticc/plasticc_pandas_ibis.py
- run_ibis_benchmark.py
- run_ibis_tests.py
- santander/santander_pandas_ibis.py
- server/server.py
- server_worker/server_worker.py
- taxi/taxibench.py
- taxi/taxibench_pandas_ibis.py
- utils/utils.py
> fix code style

- census/census_pandas_ibis.py
- run_ibis_tests.py
- utils/utils.py
> add modin-on-omnisci mode for census

- taxi/taxibench_pandas_ibis.py
Corrections needed for proper results reporting to MySQL db.
> [taxi] correct results reporting

- taxi/taxibench_pandas_ibis.py
In `Modin_on_omnisci` mode queries execution should be triggered.
> [taxi] add queries triggering for Modin_on_omnisci mode

- README.md
- h2o/h2o_modin.py
Since some bugs in modin were fixed, some h2o queries can be enabled.
> [h2o] enable some queries

- h2o/h2o_modin.py
- teamcity_build_scripts/36-h2o_groupby_pandas.sh
- teamcity_build_scripts/37-h2o_join_pandas.sh
Scripts to run H2O benchmark in CI.
> [CI] add h2o on Pandas scripts for TeamCity

- ci_requirements.yml
Pin `xgboost` to version without regression.
> [CI] pin xgboost version

- teamcity_build_scripts/30-census_modin_on_omnisci.sh
- teamcity_build_scripts/32-ny_taxi_modin_on_ray_20M_records.sh
- teamcity_build_scripts/33-ny_taxi_modin_on_omnisci_20M_records.sh
- teamcity_build_scripts/34-plasticc_modin_on_omnisci.sh
Typo fix + parameters aligning for taxi script.
> [CI] TeamCity scripts correction

- ci_requirements.yml
> [CI] unpin pandas version

- ci_requirements.yml
> [CI] Add `scikit-learn-intelex` instead of obsolete versions

- utils/utils.py
> disable ray dashboard

- census/census_pandas_ibis.py
- utils/utils.py
> use sklearnex instead of daal4py

- run_ibis_benchmark.py
- run_ibis_tests.py
- run_omnisci_benchmark.py
- utils_base_env/__init__.py
- utils_base_env/utils_base_env.py
> refactor adding SQL parameters

- report_asv_result.py
Part of #208.
Blocked by #212.
> add SQL reporter of ASV results

- ci_requirements.yml
> [CI] Pin arrow to 3.0 version

- utils/utils.py
Signed-off-by: Myachev <anatoly.myachev@intel.com>
> use native engine for omnisci backend

- environment/environment.py
- run_ibis_tests.py
> [CI] Specify channel during env creation

- run_ibis_benchmark.py
- setup.cfg
- utils/s3_client.py
- utils/utils.py
In this mode omniscripts as benchmark runner doesn't need any additional dependencies to be installed.
> Add no deps mode

- plasticc/plasticc_pandas_ibis.py
The problem was in calculating of loss value during parallel training on several partitions. Implementation of [`multi_weighted_logloss`](https://github.com/intel-ai/omniscripts/blob/ad242e7d185120c29b28f79d18b36140106bb688/plasticc/plasticc_pandas_ibis.py#L479) function supposed, that parameters `y_true` and `y_preds` have an equal lenth because all dataset is used in classic xgb case and all classification labels are presented in `y_true`.
In case Modin XGB func `multi_weighted_logloss` is called during training of each partition of the data it's not guaranteed that each partition will have all classification labels. By this reason we had an exception about mismatched shapes in [line ](https://github.com/intel-ai/omniscripts/blob/ad242e7d185120c29b28f79d18b36140106bb688/plasticc/plasticc …
> Fix Modin XGBoost for case not all classes are presented in partition

- teamcity_build_scripts/18-mortgage.sh
- teamcity_build_scripts/20-h2o_groupby_small_modin_on_ray.sh
- teamcity_build_scripts/21-h2o_groupby_small_modin_on_omnisci.sh
- teamcity_build_scripts/22-h2o_groupby_medium_modin_on_ray.sh
- teamcity_build_scripts/23-h2o_groupby_medium_modin_on_omnisci.sh
- teamcity_build_scripts/24-h2o_groupby_big_modin_on_ray.sh
- teamcity_build_scripts/25-h2o_groupby_big_modin_on_omnisci.sh
- teamcity_build_scripts/26-h2o_join_small_modin_on_ray.sh
- teamcity_build_scripts/27-h2o_join_small_modin_on_omnisci.sh
- teamcity_build_scripts/28-h2o_join_medium_modin_on_ray.sh
- teamcity_build_scripts/29-h2o_join_medium_modin_on_omnisci.sh
- teamcity_build_scripts/30-census_modin_on_omnisci.sh
- teamcity_build_scripts/31-census_modin_on_ray.sh
- teamcity_build_scripts/32-ny_taxi_modin_on_ray_20M_records.sh
- teamcity_build_scripts/33-ny_taxi_modin_on_omnisci_20M_records.sh
- teamcity_build_scripts/34-plasticc_modin_on_omnisci.sh
- teamcity_build_scripts/35-plasticc_modin_on_ray.sh
- teamcity_build_scripts/36-h2o_groupby_pandas.sh
- teamcity_build_scripts/37-h2o_join_pandas.sh
- teamcity_build_scripts/38-plasticc_modin_on_ray_modin_xgb.sh
> make bash substitution works correctly

- environment/environment.py
> FIX-#242: show output of 'conda run' command

- ci_requirements.yml
> [CI] Add tbb dependency

- h2o/h2o_modin.py
> h20: add check for empty filenames after braceexpanding

- run_modin_tests.py
> REFACTOR-#252: remove traceback.print_exc

- run_modin_benchmark.py
- utils/__init__.py
- utils/utils.py
- utils_base_env/utils_base_env.py
> REFACTOR-#261: move functionality to run benchmarks and report results from 'main' function in 'run_modin_benchmarks.py'

- teamcity_build_scripts/39-h2o_groupby_small_pandas.sh
- teamcity_build_scripts/40-h2o_join_small_pandas.sh
- teamcity_build_scripts/41-census_pandas.sh
- teamcity_build_scripts/42-ny_taxi_pandas_20M_records.sh
- teamcity_build_scripts/43-plasticc_pandas.sh
Add TeamCity scripts to launch benchmarks with pure pandas. Corresponding steps were added to TeamCity configuration.
> [CI] Add pandas launches

- run_modin_tests.py
- utils_base_env/utils_base_env.py
> REFACTOR-#255: remove 'manage_dbe_dir' option

- teamcity_build_scripts/34-plasticc_modin_on_omnisci.sh
> add MODIN_OMNISCI_FRAGMENT_SIZE into 34-plasticc_modin_on_omnisci.sh

- flyte/benchmarks/README.md
- flyte/benchmarks/scripts/taxi_flyte.py
> FIX-#280: update taxi dataset link; add 'awscli' to requirements

- flyte/benchmarks/scripts/plasticc_flyte.py
- flyte/benchmarks/scripts/santander_flyte.py
> flyte: use default datasets from the `modin-datasets` bucket

- flyte/docs/Setup and launch Flyte on AWS.md
> remove internals

- .travis.yml
> add '--diff' option for `black`

- flyte/docs/Setup and launch Flyte on AWS.md
Resolves #296 
Main changes:
* adapted to changes in Opta and Flyte
* removed unnecessary steps
* restructured into sections for reusability
* mentioned specific versions of tools and packages for reliability
> Update Flyte documentation

- .travis.yml
Signed-off-by: Myachev <anatoly.myachev@intel.com>
Closes #307
> Update python in CI

- docker/microbenchmarks-hdk/asv-runner.sh
> Ray benchmarking, update asv-runner.sh

- report/report.py
The current have error in type annotation, which leads to error during module import
> Fixed type error for report.db

- setup.cfg
Initially found in https://github.com/intel-ai/omniscripts/pull/334#discussion_r1052029972
> Remove one level of the indentation from `setup.cfg`

- .github/workflows/main.yml
> Remove run on push

- .gitignore
In response to https://github.com/intel-ai/omniscripts/pull/396#discussion_r1154847125
> Updated gitignore to typical for python

- .github/workflows/build.yml
- requirements/base.yaml
- requirements/dev_reqs.txt
- requirements/linters.txt
> Simplified requirements #412 #413

- MANIFESET.in
> Cleaned up manifest #411

- omniscripts/report/run_params.py
Currently omniscripts will fail on Macos because of failure to read host info. This patch gives warning instead of failure
> Basic support of macos hosts

- omniscripts/benchmarks/optiver_volatility/optiver_utils.py
Closes https://github.com/intel-ai/omniscripts/issues/419
> [optiver] Removed Path hotfix

- .github/workflows/build.yml
- omniscripts/arg_parser.py
- omniscripts/benchmark.py
- omniscripts/scripts/report_xlsx.py
Fixed issue when DbConfig intialized reporter without user input. Added CI to test this behavior.
Closes https://github.com/intel-ai/omniscripts/issues/423
> Fixed issue when DbConfig intialized reporter without user input

- omniscripts/__init__.py
- omniscripts/arg_parser.py
- omniscripts/benchmarks/hm_fashion_recs/candidates.py
- omniscripts/benchmarks/hm_fashion_recs/fe.py
- omniscripts/benchmarks/hm_fashion_recs/preprocess.py
- omniscripts/benchmarks/hm_fashion_recs/tm.py
- omniscripts/benchmarks/hm_fashion_recs/week_processing_benchmark.py
- omniscripts/benchmarks/optiver_volatility/benchmark.py
- omniscripts/benchmarks/optiver_volatility/optiver_utils.py
- omniscripts/benchmarks/optiver_volatility/prepare_dataset.py
- omniscripts/benchmarks/optiver_volatility/preprocess.py
- omniscripts/benchmarks/optiver_volatility/train.py
- omniscripts/scripts/benchmark_run.py
- omniscripts/timer.py
new argument is called `-verbosity X`
Closes https://github.com/intel-ai/omniscripts/issues/395
> Timer verbosity can be configured from benchmark_run arguments

- build_scripts/00-run_bench.sh
- build_scripts/h2o_ext.sh
- build_scripts/hm_fashion_recs.sh
- build_scripts/ny_taxi.sh
- build_scripts/ny_taxi_ml.sh
- build_scripts/optiver_volatility.sh
- build_scripts/plasticc.sh
Our internal CI is ready for this change
> [build_scripts]: now all benchmarks expect to store datasets in folders with the same name

- omniscripts/report/schema.py
It's necessary for hm_fashion_fecs.full
> Increased measurement length 200 -> 500

- .github/workflows/build.yml
- omniscripts/scripts/benchmark_run.py
- omniscripts/test_timer.py
- omniscripts/timer.py
- omniscripts_benchmarks/example_benchmark/benchmark_content.py
Currently with iteration > 1 TimerManager will give error because of overwrite. So with this patch we reset it.
> Added timer reset on each iteration

- timedf_benchmarks/ny_taxi/ny_taxi.py
https://github.com/intel-ai/modin-perf/actions/runs/5214809666/jobs/9412484490
> Use `numeric_only=True` for `groupby.mean`; required change for pandas>=2.0

- docs/source/04-library_tools.rst
- timedf/arg_parser.py
- timedf/backend.py
- timedf/scripts/benchmark_run.py
- timedf_benchmarks/census/census_pandas.py
- timedf_benchmarks/example_benchmark/benchmark_content.py
- timedf_benchmarks/hm_fashion_recs/candidates.py
- timedf_benchmarks/hm_fashion_recs/fe.py
- timedf_benchmarks/hm_fashion_recs/hm_utils.py
- timedf_benchmarks/hm_fashion_recs/lfm.py
- timedf_benchmarks/hm_fashion_recs/notebook.py
- timedf_benchmarks/hm_fashion_recs/preprocess.py
- timedf_benchmarks/ny_taxi/ny_taxi.py
- timedf_benchmarks/ny_taxi_ml/ny_taxi_ml.py
- timedf_benchmarks/optiver_volatility/prepare_dataset.py
- timedf_benchmarks/optiver_volatility/preprocess.py
- timedf_benchmarks/optiver_volatility/train.py
- timedf_benchmarks/plasticc/plasticc_pandas_modin.py
Also rename of pandas_backend to backend, since we have so many backends now
> HDK as a new backend

- timedf/modin_utils.py
Otherwise, Ray always uses as many processes as possible.
> Fix Ray initialization

- timedf_benchmarks/hm_fashion_recs/README.md
- timedf_benchmarks/hm_fashion_recs/candidates.py
- timedf_benchmarks/hm_fashion_recs/fe.py
- timedf_benchmarks/hm_fashion_recs/hm_utils.py
Fixed in https://github.com/modin-project/modin/pull/6307
> H&M: remove iloc workaround

- requirements/base.txt
- requirements/base.yaml
- requirements/dev_reqs.txt
With latest polars==0.18.11 we have problem during installation, so we fix it for now
> Fixed polars version

- requirements/dev_reqs.txt
This will avoid problems with unexpected update of dev environment that break code checks
Updating this file will be done semi-manually with dependabot
> Fixed requirements for dev env

- timedf/backends/modin_utils.py
- timedf/benchmark_utils.py
- timedf/report/run_params.py
- timedf/scripts/benchmark_run.py
Fixing issue #546 by adding a new class LaunchedProcesses to keep track of all launched processes.
> Fix:546 reporting max_memory_mb for Unidist backend

- timedf/backends/modin_utils.py
Refactoring a minor issue with black check failing in previous PR
> REFACTOR Black minor fix
