intel-ai/timedf

ci_requirements.yml
One of synthetic benchmarks start failed after omnisci bumped pymapd version >= 0.20.0
I think we should do the same.
Omnisci commit hash with the change: 6ca47d0f6437061a560dc54215569af9c26ee215
=> SUPP: update pymapd version >= 0.20.0

server/server.py
Because omnisci start to fail:
[Step 5/13] OMNISCI>> Usage Error: unrecognised option '--enable-lazy-fetch=false'
=> Disable --enable-lazy-fetch omnisci server option

run_ibis_tests.py, server/server.py
Current OmniSciDB master doesn't know --enable-columnar flag
=> Correction to run CI on the OmniSciDB master

environment/environment.py, server/server.py
Before the change, running `python run_ibis_tests.py -h` from outside conda environment or _not_ from the `base` environment lead to cryptic error message like
```
Traceback (most recent call last):                                                       
File "run_ibis_tests.py", line 5, in <module>                                          
from environment import CondaEnvironment                                             
File "omniscripts/environment/__init__.py", line 1, in <module>    
from .environment import CondaEnvironment                                            
File "omniscripts/environment/environment.py", line 6, in <module> 
from conda.cli.python_api import Commands, run_command                               
ModuleNotFoundError: No module named 'conda' …
```
=> Replace confusing error message with direct instructions

run_ibis_benchmark.py
When -no_ibis is selected, validation should be always False no matter
what is specified on command line.
=> Pass "validation" parameter unconditionally to benchmarks

mortgage/__init__.py, mortgage/mortgage_ibis.py, mortgage/mortgage_pandas.py, mortgage/mortgage_runner.py, mortgage/transform-data.py, run_ibis_benchmark.py, run_ibis_tests.py, utils/utils.py
Current limitations:
* `-import_mode` - only `fsi` is supported
* `-dfiles_num` must be 1 for Ibis part
* No validation is performed
Parameters are interpreted as follows:
* `-data_file`: path to the _directory_ containing Mortgage data
* `-dfiles_num`: how many quarters to load
* `-table`: _prefix_ of tables to be made in OmniSci
Ibis version requires `-omnisci_run_kwargs enable-union=1` to be set.
Best performance is achieved with flags `-columnar_output True -lazy_fetch False -multifrag_rs True`.
Currently required branches of components are:
* OmniSci: https://github.com/intel-go/omniscidb/tree/ienkovich/develop-merged-with-master
* Ibis: https://github.com/intel-go/ibis/tree/vnlitvinov/enable-union
I think validation could be added in a separate PR.
=> Add Mortgage to benchmarks

mortgage/mortgage_pandas.py
`timer()` reports time in seconds, but we're reporting them as milliseconds. This leads to incorrect time being displayed.
=> Transform seconds to milliseconds in Mortgage ML to fix reporting

run_ibis_benchmark.py
Ibis requirement for all cases is too cubersome. For pandas and modin
testing ibis is not required so no need to import it unconditionally.
=> Move OmnisciServer and OmnisciServerWorker out of no_ibis path

run_ibis_benchmark.py, run_ibis_tests.py
ipc_conn flag is not forwarded from run_ibis_tests to run_ibis_benchmark
=> ipc_conn not forwarding bug fix

run_ibis_benchmark.py, run_ibis_tests.py
Allows to create omniscripts commit hash dependencies graphs in Grafana.
=> Omniscripts commit hash reporting to the MySQL database

run_ibis_benchmark.py
Queries results should be reported only once.
=> reporting correction

census/census_pandas_ibis.py, santander/santander_pandas_ibis.py, taxi/taxibench_pandas_ibis.py, utils/__init__.py, utils/utils.py
- now all temporary files should be created via added `get_tmp_filepath` it creates temporary file with the specified name and UID suffix at `repository_root/tmp`. User of `get_tmp_filepath` is responsible for deleting that file
- files combining at Taxi were taken out in a separate class `FilesCombiner`
- `get_dir` were reformated to `create_dir`, with that function you create or get existing directory at the root of repository
=> unique tmp files

teamcity_build_scripts/14-ny_taxi_pandas_ibis.sh
Now taxi benchmark supports default fsi import mode.
=> [taxi] remove explicit -import_mode flag passing

mortgage/mortgage_ibis.py, mortgage/mortgage_pandas.py, mortgage/mortgage_runner.py
1. For Pandas, fix the problem of iterating mortgage data files for the specified num of quarters.
2. For Ibis, allow user to specify `dfiles_num` to be greater than 1, iterate the files for acq and perf to preprocess the data, concat the results into one DateFrame.
=> Support processing multiple-quarters of data for mortgage (pandas and ibis)

utils/utils.py
Splittext returns extension with "." so adjusted comparison in FilesCombiner
=> Proper work with file extension

mortgage/mortgage_pandas.py
* Combine multiple single-column drops into single multi-column drop
* Do not get a type of a column when we already know it from `df.dtypes.items()`
All the changes should have minimal impact on local run and save a few percent of runtime when run scaled-out by Modin.
=> Add some small perf fixes for Mortage

mortgage/mortgage_pandas.py
Other benchmarks in omniscripts calculate ETL time without accounting data import time, so Mortgage methodology was aligned to match common methodology.
=> [Mortgage] Correction of etl time calculation

utils/utils.py
We need to initialize Calcite before benchmarks runs to get correct timing results in `Modin_on_omnisci` mode.
=> [utils] Calcite initialization for Modin_on_omnisci mode

mortgage/mortgage_pandas.py
With modin-project/modin#2129 merged we don't need this hack anymore for Modin. Not sure if it doesn't break some other targets.
=> Remove hack for mortgage delimiter

run_ibis_tests.py
Currently we faced with package compatibility error https://teamcity-or.intel.com/viewLog.html?buildId=6629084&buildTypeId=Golang_Omniscidb_TestsFunctionalTestingPrNn&tab=buildLog&_focus=1845, introduced workaround aims to fix this issue.
=> [CI] add protobuf upgrading step

run_ibis_benchmark.py, run_ibis_tests.py, teamcity_build_scripts/14-ny_taxi_pandas_ibis.sh, teamcity_build_scripts/19-build_modin_dbe.sh, teamcity_build_scripts/20-h2o_groupby_small_modin_on_ray.sh, teamcity_build_scripts/21-h2o_groupby_small_modin_on_omnisci.sh, teamcity_build_scripts/22-h2o_groupby_medium_modin_on_ray.sh, teamcity_build_scripts/23-h2o_groupby_medium_modin_on_omnisci.sh, teamcity_build_scripts/24-h2o_groupby_big_modin_on_ray.sh, teamcity_build_scripts/25-h2o_groupby_big_modin_on_omnisci.sh, teamcity_build_scripts/26-h2o_join_small_modin_on_ray.sh, teamcity_build_scripts/27-h2o_join_small_modin_on_omnisci.sh, teamcity_build_scripts/28-h2o_join_medium_modin_on_ray.sh, teamcity_build_scripts/29-h2o_join_medium_modin_on_omnisci.sh, teamcity_build_scripts/30-census_modin_on_omnisci.sh, teamcity_build_scripts/31-census_modin_on_ray.sh, teamcity_build_scripts/32-ny_taxi_modin_on_ray_20M_records.sh, teamcity_build_scripts/33-ny_taxi_modin_on_omnisci_20M_records.sh
In order to create performance CI to compare benchmarks results in `Modin_on_omnisci` vs `Modin_on_ray` modes we need next changes:
1) Additional TeamCity scripts in these two modes should be added (for now covered H2O, Census and NYC taxi benchmarks).
2) Modin commit hash also should be added since modin changes can affect benchmark performance.
3) There is no need to mark `executable` flag as required - when `task` flag is set to only `benchmark`, `executable` can be omitted.
=> [CI] add scripts for Modin_on_omnisci mode

taxi/taxibench_pandas_ibis.py
This triggering is needed to perform data import exactly on import step, not on queries execution step.
=> [taxi] correct data import triggering for Modin_on_omnsici mode

run_ibis_tests.py
This PR resolve also next problem.
```python
from .session import get_session, AioSession
File "/miniconda3/envs/test-env/lib/python3.7/site-packages/aiobotocore/session.py", line 1, in <module>
from botocore.session import Session, EVENT_ALIASES, ServiceModel, UnknownServiceError
ImportError: cannot import name 'EVENT_ALIASES' from 'botocore.session' (/miniconda3/envs/test-env/lib/python3.7/site-packages/botocore/session.py)
```
Package `botocore` is a dependency of package `s3fs`, which was installed via the conda (as a `omniscripts` dependency), and also installed via pip (as a `modin` dependency), because of this, the incompatibility indicated above appeared.
=> install modin dependencies via conda

utils/utils.py
We should import sklearn only once, otherwise ML portion execution time measurement can be affected by import satge.
=> [utils] Correct sklearn import

utils/utils.py
Plasticc ML portion fails without this change because `import daal4py` doesn't import `sklearn` (in Census `sklearn` imported in the benchmark runner https://github.com/intel-ai/omniscripts/blob/master/census/census_pandas_ibis.py#L276).
=> [Plasticc] correct sklearn import

mortgage/mortgage_pandas.py, teamcity_build_scripts/18-mortgage.sh
Currently Mortgage etl_pandas fails with message for both Modin and Pandas
` ValueError: invalid literal for int() with base 10: '100007365142,R,JPMORGAN CHASE BANK_ NA,8,75000,360,1999-12-01,2000-02-01,79,,1,62,763,N,R,SF,1,P,PA,173,,FRM,,,N,200001'`
In order to fix it, we should pass original Mortgage dataset for etl_pandas (with #161 merged etl_pandas should use dataset with `|` delimiter).
=> [Mortgage] use original dataset for etl_pandas

plasticc/plasticc_pandas_ibis.py
I propose to remove sort from the Modin version of PlastiCC. We don't have this sort in the Ibis version and it works fine. Removing it from the Modin version would allow us to compare Ibis and Modin ETL time.
=> Don't sort in plasticc groupby

ci_requirements.yml
`arrow` and `arrow-cpp` should be pinned to newer versions to avoid problems with dependencies solving during installing of Modin packages (modin was updated to `arrow==1.0`).
=> [CI] pin arrow to 1.0 version

teamcity_build_scripts/21-h2o_groupby_small_modin_on_omnisci.sh, teamcity_build_scripts/23-h2o_groupby_medium_modin_on_omnisci.sh, teamcity_build_scripts/25-h2o_groupby_big_modin_on_omnisci.sh, teamcity_build_scripts/27-h2o_join_small_modin_on_omnisci.sh, teamcity_build_scripts/29-h2o_join_medium_modin_on_omnisci.sh, teamcity_build_scripts/30-census_modin_on_omnisci.sh, teamcity_build_scripts/33-ny_taxi_modin_on_omnisci_20M_records.sh, teamcity_build_scripts/34-plasticc_modin_on_omnisci.sh
It was found that benchmarks execution halted if it was ran using `run_ibis_tests.py` script (script uses `conda run` to run `run_ibis_benchmark.py`). Reproducer:
```
import os
os.environ["MODIN_ENGINE"] = "ray"
os.environ["MODIN_BACKEND"] = "omnisci"
os.environ["MODIN_EXPERIMENTAL"] = "True"
import modin.pandas as pd
def init_modin_on_omnisci(pd):
data = {"a": [1, 2, 3]}
df = pd.DataFrame(data)
df = df + 1
_ = df.index
init_modin_on_omnisci(pd)
```
=> [CI] Avoid using `conda run` command for Modin_on_omnisci engine in TeamCity scripts

h2o/h2o_modin.py, run_ibis_benchmark.py, teamcity_build_scripts/33-ny_taxi_modin_on_omnisci_20M_records.sh
We need slightly modify TeamCity NYX taxi benchmark script and `run_ibis_benchmark.py` for proper CI work with "`conda run` workaround" mentioned in https://github.com/intel-ai/omniscripts/pull/179.
=> [CI] `conda run` workaround fix

census/census_pandas_ibis.py, environment/environment.py, h2o/h2o_modin.py, mortgage/mortgage.py, mortgage/mortgage_runner.py, mortgage/transform-data.py, plasticc/plasticc_pandas_ibis.py, run_ibis_benchmark.py, run_ibis_tests.py, santander/santander_pandas_ibis.py, server/server.py, server_worker/server_worker.py, taxi/taxibench_pandas_ibis.py
`sys.exit` calls were removed to eliminate false positive CI checks, also unnecessary tracebacks prints were removed (now it is printed only in `run_ibis_tests.py` only).
=> [CI] remove sys.exit calls

report/report.py
It was found that CI fails with message
`_mysql_connector.MySQLInterfaceError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'System VARCHAR(500) NOT NULL,CPUCount VARCHAR(500) NOT NULL,CPUModel VARCHAR(500' at line 1`
Empirically was found that SQL query fails because of `System` field name (some time ago OS on machine with SQL server was updated and MySQL probably was updated as well and now `System` name can be prohibited). So `System` name was replaced `OS` name for omniscripts and MySQL tables.
=> [CI] rename reporting field

ci_requirements.yml
It was found that after Pandas 1.2.0 was released, NYC taxi benchmark using OmniSciDB/Ibis failed, so we are trying to pin Pandas version to fix it.
=> pin pandas version

run_ibis_tests.py
We need to correct env file since it was renamed in modin  https://github.com/modin-project/modin/pull/2668.
=> [CI] rename modin env file

ci_requirements.yml, run_ibis_tests.py, utils_base_env/__init__.py, utils_base_env/utils_base_env.py
`xgboost` dependency was added in modin, so omnsicripts need to track it to avoid dependencies conflicts.
Also `hiyapyco` package was removed and environment update replaced with `conda env update` statement.
=> [CI] correct xgboost dependency

ci_requirements.yml
`intel-ai/omniscidb` now supports `pyarrow 2.0`, so version here can be switched too.
=> [CI] pin pyarrow to 2.0 version

ci_requirements.yml
It was found that `daal` version not correlates with installed `daal4py` version and after new `daal` release, compatibility of `daal` and `daal4py` became broken, reproducer:
```
conda install daal4py=0.2020.2 -c intel
python -c "import daal4py.sklearn.linear_model as lm"
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/miniconda3/envs/test/lib/python3.7/site-packages/daal4py/__init__.py", line 2, in <module>
from _daal4py import *
ImportError: libdaal_core.so: cannot open shared object file: No such file or directory
conda list | grep daal
daal                      2021.1.1               intel_79    intel
daal4py                   0.2020.2         py37h533f8aa_7    intel
```
So we are pinning …
=> [CI] pin daal

environment/environment.py, run_ibis_tests.py
Currently `CondaEnvironment.create` (function that responsible for conda env creation) doesn't handle python version that was defined by user. This PR fixes this issue.
=> [CI] Correct conda env creation

docker/Dockerfile.omnisci-from-conda, docker/Dockerfile.ray
All benchmarks in CI should be run in docker containers. These files are necessary to implement it this way.
=> Added dockerfiles to run benchmarks in ray and omnisci from conda configurations

run_ibis_tests.py, taxi/taxibench_pandas_ibis.py
Also corrected `OmnisciServer` import to fix taxi bench.
=> [CI] Avoid Modin dependencies installation and use correct Omnisci engine name

ci_requirements.yml
`omniscidb` from `https://github.com/intel-ai/omniscidb/tree/modin` started to work with `pyarrow==5.0`, so we should update `omniscripts` env file that used in tests.
=> update pyarrow: 3.0 -> 5.0

environment/environment.py
=> REFACTOR: use '--cwd' option of conda 'run' command instead of `execute_process`

run_modin_tests.py
Resolves #248 
Main changes:
* `--env_name` now optional
* The work on running the code in the conda environment has been changed. Previously, a `run_modin_benchmarks.py` was launched in Conda environment, but now `run_modin_tests` itself is launched in Conda environment.
=> make env management in 'run_modin_tests.py' optional

utils/utils.py
This PR makes `no-deps` mode default. Now `braceexpand` and `s3fs` are used only if they are available, otherwise our reduced version of `braceexpand` will be used. In the cases when S3 files are passed and `s3fs` is not available, exception is raised.
=> Rework no-deps mode

README.md, run_modin_tests.py, utils_base_env/utils_base_env.py
pandas and Modin now requires minimum python 3.8 version, so we need to meet these requirement too.
OmniSci in the CI configuration now is built with python 3.8 too.
=> Increase minimum python version

report/report.py
We have started to use TeamCity agents inside containers, but the command `socket.gethostname()` inside a container outputs container id, that breaks results representation.
=> Correct reporting

taxi/taxibench_pandas_modin.py
Taking columns in the exact order as they're stored in the frame allows us to skip [labels reordering](https://github.com/modin-project/modin/blob/c30ab4c132295b1e168fbb06a050c76554759e11/modin/core/dataframe/pandas/dataframe/dataframe.py#L859) in the following `.groupby()` call which inquiries data reshuffling.
Signed-off-by: Dmitry Chigarev <dmitry.chigarev@intel.com>
=> [TAXI]: Take columns in the exact order as they're stored

taxi/taxibench_pandas_modin.py
Accumulating as much as possible into a single API call is good for Modin's perf
Signed-off-by: Dmitry Chigarev <dmitry.chigarev@intel.com>
=> [TAXI] Use `as_index=False` in groupby instead of `.reset_index()` after groupby

docker/e2e-hdk/README.md, docker/e2e-hdk/all.sh
Now `DATASETS_ROOT` needs to be provided before running `all.py`, or user have to edit `all.py` beforehand. The first line in `all.sh` is responsible for that, since it sets `-u` flag and `DATASETS_ROOT` is used in the script without exporting it first.
=> DATASETS_ROOT is now required to be defined by `all.sh`

docker/e2e-hdk/Dockerfile, docker/e2e-hdk/README.md, docker/e2e-hdk/all.sh, docker/e2e-hdk/load_data.sh, docker/e2e-hdk/run_benchmarks.sh, docker/e2e-hdk/run_docker.sh
This PR updates docker folder with reproduction of selected benchmarks, adding xlsx generation based on benchmark results. It depends on https://github.com/intel-ai/omniscripts/pull/337
=> Docker benchmark reproduction now generates xlsx and take median of 3 iterations

.github/workflows/build.yml, build_scripts/00-run_bench.sh, build_scripts/ny_taxi_ml.sh, build_scripts/plasticc.sh, omniscripts/__init__.py, omniscripts/arg_parser.py, omniscripts/benchmark.py, omniscripts/benchmarks/ny_taxi/taxibench_pandas_modin.py, omniscripts/scripts/benchmark_run.py
With this patch Benchmark classes can define their own parser parts, that will read arguments, specific to them. So, for instance `ny_taxi` can define and read it's own arguments. This patch contains example usage with `ny_taxi` benchmark.
Closes https://github.com/intel-ai/omniscripts/issues/418
=> Benchmarks now support unique arguments

docker/microbenchmarks-hdk/asv-runner.sh
Experimental mode is set automatically - details in https://github.com/modin-project/modin/pull/3670.
We also don't want to enable experimental mode for Ray.
=> ASV: remove `export MODIN_EXPERIMENTAL=true` from `asv-runner.sh`

build_scripts/00-run_bench.sh
When pandas mode is  "Modin_on_unidist_mpi", Benchmark script should be called with mpiexec.
=> build_scripts now support mpiexec for unidist

requirements/dev_reqs.txt, requirements/reporting.txt, requirements/reporting.yaml
Previously we used `sqlalchemy==1.4.0`, which is quite outdated
=> Set latest sqlalchemy==1.4.*
